add bgcolor to turtul module
UpsilonNumworks/Upsilon pull request #367
Opened 2024-06-04 19:40 UTC by cartoone222

2024-06-04 19:44 UTC, cartoone222 commented
is for do this issue https://github.com/UpsilonNumworks/Upsilon/issues/301

2024-06-05 14:11 UTC, Yaya-Cout requested changes
Also, can you add the function to the toolbox ? It should also automatically setup the auto-completion, if I remember correctly. If you don't know how to do that, it's not a problem, it's not required for it to work and I can do it myself.

2024-06-05 14:11 UTC, Yaya-Cout commented on python/port/mod/turtle/turtle.h
> +  static constexpr KDColor k_defaultColorBG = KDColorYellow;
Why are you overwriting the default color ? You should rather use the theme value.

2024-06-05 14:32 UTC, cartoone222 commented on python/port/mod/turtle/turtle.h
> +  static constexpr KDColor k_defaultColorBG = KDColorYellow;
sory is an forgoten element of debuginig. also yes i can try to add to the toolbox i try to take time to try on thats in the next day

2024-06-06 17:14 UTC, Yaya-Cout requested changes
The toolbox seem right. You only need to change the default background color.

2024-06-06 17:14 UTC, Yaya-Cout commented on python/port/mod/turtle/turtle.h
> +  static constexpr KDColor k_defaultColorBG = KDColorWhite;
Default BG is not always white, it depend of the theme. For example, using Omega Kawaii (left is current Upsilon version and right is your version) : 
![Left : Normal simulator, with Omega Kawaii Background ; Right : Simulator built from this pull request, with white background](https://github.com/UpsilonNumworks/Upsilon/assets/67095734/33c6db5e-acae-46af-ad8c-07eb4430ee90)
You can add `THEME_NAME=omega_kawaii THEME_REPO=https://github.com/Omega-Numworks-Prod/Omega-Kawaii-Theme` to your build command to test, after doing a full clean (`make cleanall`).
You should check, but I think the default background color is `Palette::CodeBackground`.

2024-06-07 07:06 UTC, Yaya-Cout requested changes
Everything is OK, but you should just remove the Omega Kawaii Theme from the repo (themes should only be cloned at build time)

2024-06-09 06:54 UTC, Yaya-Cout approved these changes
LGTM, will merge after the CI.

2024-06-09 07:01 UTC, merged