add an option for disable shift + clear
UpsilonNumworks/Upsilon pull request #368
Opened 2024-06-10 12:25 UTC by cartoone222

i have code this issue https://github.com/UpsilonNumworks/Upsilon/issues/285

2024-06-17 18:46 UTC, Yaya-Cout requested changes
There is some things to change and I didn't built, but it looks OK.

2024-06-17 18:46 UTC, Yaya-Cout commented on escher/src/text_area.cpp
> +    if (GlobalPreferences::sharedGlobalPreferences()->clearalphalockshift()){
```suggestion
    if (GlobalPreferences::sharedGlobalPreferences()->clearalphalockshift()) {
```

2024-06-17 18:46 UTC, Yaya-Cout commented on apps/settings/base.en.i18n
> +Clearshiftlock = "shortcut shift + clear"
Would it be possible to capitalize first letter ? (in others languages too)

2024-06-17 18:46 UTC, Yaya-Cout commented on apps/global_preferences.h
> +  void setclearalphalockshift(bool clearalphalockshift) { m_clearalphalockshift = clearalphalockshift; }
Why alphalock ? Isn't this about Shift + Clear ?

2024-06-18 14:13 UTC, cartoone222 commented
i hope i havent break all

2024-06-18 14:14 UTC, cartoone222 commented
cool is ok

2024-06-18 16:40 UTC, Yaya-Cout reviewed
Also, why is it named "clearalphalockshift" ?

2024-06-18 16:40 UTC, Yaya-Cout commented on apps/settings/sub_menu/code_options_controller.cpp
> +  }else if (index == 2){
```suggestion
  }else if (index == 2) {
```

2024-06-18 16:40 UTC, Yaya-Cout commented on escher/src/text_area.cpp
> +    if (GlobalPreferences::sharedGlobalPreferences()->clearshift()){
```suggestion
    if (GlobalPreferences::sharedGlobalPreferences()->clearshift()) {
```

2024-06-18 16:54 UTC, cartoone222 commented
ok is beacaus i have change function name and e not variable name

2024-06-18 17:07 UTC, cartoone222 commented
thank you for your patience I think everything is ok now

2024-09-23 19:19 UTC, cartoone222 commented
why the test dosent complet ?

2024-09-23 19:29 UTC, quentinguidee requested changes

2024-09-23 19:29 UTC, quentinguidee commented on apps/global_preferences.h
> +  void setclearshift(bool clearalphashift) {  m_clearkshift = clearalphashift; }
Better to use camelCase here for consistency

2024-09-23 19:29 UTC, quentinguidee commented on apps/global_preferences.h
>      m_brightnessLevel(Ion::Backlight::MaxBrightness),
```suggestion
    m_syntaxhighlighting(true),
    m_clearkshift(true),
    m_brightnessLevel(Ion::Backlight::MaxBrightness),
```

2024-09-23 19:29 UTC, quentinguidee commented on apps/global_preferences.h
> +  bool  m_clearkshift;
Same (camelCase)

2024-09-23 19:29 UTC, quentinguidee commented on apps/settings/base.de.i18n
> +Clearshift = "Tastenkombination Umschalt + Löschen"
Same (PascalCase for all i18n files)

2024-09-23 19:29 UTC, quentinguidee commented on apps/settings/sub_menu/code_options_controller.cpp
> +  }else if (index == 2) {
```suggestion
  } else if (index == 2) {
```

2024-09-24 10:55 UTC, cartoone222 commented
thx

2025-03-08 11:01 UTC, Yaya-Cout requested changes
Please apply given suggestions before marking reviews as resolved and requesting a new review

2025-03-08 11:01 UTC, Yaya-Cout commented on apps/global_preferences.h
> +  void setclearshift(bool clearalphashift) {  m_clearkshift = clearalphashift; }
Can you explain what the `k` in `m_clearkshift` means? Also, avoid doubles spaces

```suggestion
  bool clearshift() const { return m_clearkshift; }
  void setclearshift(bool clearalphashift) { m_clearkshift = clearalphashift; }
```

2025-03-08 11:01 UTC, Yaya-Cout commented on apps/global_preferences.h
> +  bool  m_clearkshift;
```suggestion
  bool m_clearkshift;
```

2025-03-08 11:01 UTC, Yaya-Cout commented on apps/settings/base.de.i18n
> +Clearshift = "Tastenkombination Umschalt + Löschen"
Still not fixed (should be `ClearShift` instead of `Clearshift`)

2025-03-08 11:01 UTC, Yaya-Cout commented on apps/settings/sub_menu/code_options_controller.cpp
> +  }else if (index == 2) {
Still not fixed

2025-03-08 11:01 UTC, Yaya-Cout commented on apps/global_preferences.h
> +  void setclearshift(bool clearalphashift) {  m_clearkshift = clearalphashift; }
Still not fixed (should be `setClearShift` and `clearShift`)

2025-03-20 15:05 UTC, cartoone222 commented
I think i have fix all. sorry for the last time.

2025-03-29 09:14 UTC, Yaya-Cout reviewed
I could merge the code right now, just a few i18n edits to stay consistent.

2025-03-29 09:14 UTC, Yaya-Cout commented on apps/settings/base.de.i18n
> +ClearShift = "Tastenkombination Umschalt + Löschen"
I don't think shift + clear should be translated, as it's the text written on the keyboard (or French translation should follow the same translations rules as others languages to stay consistent).
```suggestion
ClearShift = "Tastenkombination shift + clear"
```

2025-03-29 09:14 UTC, Yaya-Cout commented on apps/settings/base.es.i18n
> +ClearShift = "Atajo de cambio + borrar"
```suggestion
ClearShift = "Atajo de shift + clear"
```

2025-03-29 09:14 UTC, Yaya-Cout commented on apps/settings/base.hu.i18n
> +ClearShift = "Gyorsbillentyű eltolás + törlés"
```suggestion
ClearShift = "Gyorsbillentyű shift + clear"
```

2025-03-29 09:14 UTC, Yaya-Cout commented on apps/settings/base.it.i18n
> +ClearShift = "Scorciatoia Maiusc + Cancella"
```suggestion
ClearShift = "Scorciatoia shift + clear"
```

2025-03-29 09:14 UTC, Yaya-Cout commented on apps/settings/base.nl.i18n
> +ClearShift = "Sneltoets shift + wissen"
```suggestion
ClearShift = "Sneltoets shift + clear"
```

2025-03-29 09:14 UTC, Yaya-Cout commented on apps/settings/base.pt.i18n
> +ClearShift = "Shift de atalho + limpar"
```suggestion
ClearShift = "Shift de shift + clear"
```

2025-03-29 09:14 UTC, Yaya-Cout commented on apps/global_preferences.h
> +  bool m_clearkshift;
Can you explain why you are using `m_clearkshift` and not just `m_clearShift`?

2025-03-30 13:44 UTC, cartoone222 commented
i have fix the name

2025-03-31 18:15 UTC, Yaya-Cout approved these changes
LGTM, I just forgot about the English translation during my last review. I've tested on the simulator, everything seems fine and ready to merge

2025-03-31 18:15 UTC, Yaya-Cout commented on apps/settings/base.en.i18n
> +ClearShift = "Shortcut shift + clear"
```suggestion
ClearShift = "Shift + clear shortcut"
```

2025-03-31 18:17 UTC, merged